version: '3.3'

services:
   web:
    build: .
    ports:
     - "5000:8000"
    volumes:
     - .:/code:rw,cached
     - ./var:/code/var:rw
    depends_on:
     - db
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     ports:
       - "4306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: supersecret
       MYSQL_DATABASE: image-gallery
       MYSQL_USER: cct
       MYSQL_PASSWORD: secret

volumes:
    db_data:
